# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouteille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire', max_digits=6, verbose_name='prix')),
                ('contenance', models.DecimalField(blank=True, decimal_places=1, help_text='contenance', max_digits=4, verbose_name='contenance')),
                ('provenance', models.CharField(blank=True, help_text='provenance de la bouteille', max_length=255, verbose_name='provenance')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vin')),
            ],
        ),
    ]
